version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - amimart
      - ccamel
      - fredericvilcot
    assignees:
      - amimart
      - ccamel
      - fredericvilcot
